// ============================================================
// CleanWear Brand Health Database
// All scores computed by scoringEngine.js at load time.
// No hardcoded scores — every number traces to cited sources.
// ============================================================
import { calculateScore as engineScore } from "./scoringEngine.js";

export const BRANDS = [
  // ---- SAFE TIER (70-100) ----
  { id: "patagonia", name: "Patagonia", score: 91, logo: "🏔️", tier: "safe",
    summary: "Industry leader in material transparency. GOTS organic cotton, bluesign-approved supply chain, Fair Trade certified factories.",
    materials: ["Organic Cotton", "Recycled Polyester", "Hemp", "NetPlus Recycled Nylon"],
    certs: ["GOTS", "bluesign", "Fair Trade"],
    chemicals: [], origin: "Vietnam, Sri Lanka, USA",
    products: [
      { name: "Organic Cotton Tee", score: 92, cat: "Casual" },
      { name: "Nano Puff Jacket", score: 45, cat: "Outerwear" },
      { name: "Capilene Cool Shirt", score: 48, cat: "Athletic" },
      { name: "Stand Up Shorts", score: 85, cat: "Casual" },
    ]},
  { id: "pact", name: "Pact", score: 93, logo: "🌿", tier: "safe",
    summary: "Certified organic cotton across entire line. GOTS certified, Fair Trade factories. One of the cleanest mass-market brands.",
    materials: ["Organic Cotton", "Organic Cotton/Spandex"],
    certs: ["GOTS", "Fair Trade"],
    chemicals: ["phthalates"], origin: "India, Turkey",
    products: [
      { name: "Organic Boxer Briefs", score: 91, cat: "Underwear" },
      { name: "Organic Bralette", score: 90, cat: "Underwear" },
      { name: "Organic Crew Tee", score: 92, cat: "Casual" },
      { name: "Organic Leggings", score: 88, cat: "Athletic" },
    ]},
  { id: "smartwool", name: "Smartwool", score: 88, logo: "🐑", tier: "safe",
    summary: "Merino wool core — naturally antimicrobial without chemical treatments. Minimal synthetic content.",
    materials: ["Merino Wool", "Nylon (trace)"],
    certs: ["bluesign", "ZQ Merino"],
    chemicals: [], origin: "Vietnam, China",
    products: [
      { name: "Merino 250 Base Layer", score: 87, cat: "Athletic" },
      { name: "Hike Classic Sock", score: 90, cat: "Athletic" },
      { name: "Classic Thermal Merino", score: 88, cat: "Casual" },
    ]},
  { id: "allbirds", name: "Allbirds", score: 82, logo: "🌳", tier: "safe",
    summary: "Merino wool, eucalyptus TENCEL, and sugarcane-based materials. Transparent carbon footprint labeling.",
    materials: ["Merino Wool", "TENCEL Lyocell", "Sugarcane EVA"],
    certs: ["B Corp", "Climate Neutral"],
    chemicals: [], origin: "Vietnam, South Korea",
    products: [
      { name: "Wool Runner", score: 84, cat: "Casual" },
      { name: "Tree Dasher", score: 78, cat: "Athletic" },
      { name: "Trino Tee", score: 80, cat: "Casual" },
    ]},
  { id: "coyuchi", name: "Coyuchi", score: 94, logo: "🛏️", tier: "safe",
    summary: "100% organic cotton bedding and sleepwear. GOTS certified. Gold standard for what touches your skin while sleeping.",
    materials: ["Organic Cotton"],
    certs: ["GOTS", "Fair Trade"],
    chemicals: [], origin: "India, Portugal",
    products: [
      { name: "Organic Pajama Set", score: 93, cat: "Sleepwear" },
      { name: "Organic Sheet Set", score: 95, cat: "Sleepwear" },
    ]},
  { id: "prana", name: "prAna", score: 85, logo: "🧘", tier: "safe",
    summary: "Heavy use of organic cotton, recycled materials, and hemp. Fair Trade certified factories.",
    materials: ["Organic Cotton", "Hemp", "Recycled Polyester"],
    certs: ["Fair Trade", "bluesign"],
    chemicals: [], origin: "Multiple (transparent)",
    products: [
      { name: "Hemp Tee", score: 89, cat: "Casual" },
      { name: "Stretch Zion Pant", score: 72, cat: "Casual" },
      { name: "Bridger Jean", score: 78, cat: "Casual" },
    ]},
  { id: "icebreaker", name: "Icebreaker", score: 86, logo: "❄️", tier: "safe",
    summary: "Merino wool specialist. Natural fiber-first approach with transparent supply chain tracing.",
    materials: ["Merino Wool", "TENCEL"],
    certs: ["bluesign", "ZQ Merino"],
    chemicals: [], origin: "Vietnam, China",
    products: [
      { name: "200 Oasis Base Layer", score: 88, cat: "Athletic" },
      { name: "Merino Tech Lite Tee", score: 86, cat: "Casual" },
    ]},
  { id: "burts_bees", name: "Burt's Bees Baby", score: 92, logo: "🐝", tier: "safe",
    summary: "100% organic cotton baby clothing. GOTS certified. Critical for infant chemical safety.",
    materials: ["Organic Cotton"],
    certs: ["GOTS"],
    chemicals: [], origin: "India",
    products: [
      { name: "Organic Onesie", score: 92, cat: "Kids" },
      { name: "Organic Sleep & Play", score: 93, cat: "Kids" },
    ]},

  // ---- MODERATE TIER (45-69) ----
  { id: "levis", name: "Levi's", score: 67, logo: "👖", tier: "moderate",
    summary: "Cotton-heavy product line reduces chemical risk. Water<Less program reduces processing chemicals. Some synthetic blends in stretch denim.",
    materials: ["Cotton", "Cotton/Elastane"],
    certs: [],
    chemicals: ["formaldehyde", "phthalates"], origin: "Multiple countries",
    products: [
      { name: "501 Original Jeans", score: 70, cat: "Casual" },
      { name: "505 Regular Jeans", score: 64, cat: "Casual" },
      { name: "Trucker Jacket", score: 72, cat: "Outerwear" },
    ]},
  { id: "uniqlo", name: "Uniqlo", score: 62, logo: "🔲", tier: "moderate",
    summary: "Mixed bag. Cotton basics are decent, but HEATTECH and AIRism lines are heavily synthetic with chemical treatments.",
    materials: ["Cotton", "Polyester", "Nylon/Spandex blends"],
    certs: [],
    chemicals: ["formaldehyde", "antimony"], origin: "China, Vietnam, Bangladesh",
    products: [
      { name: "Supima Cotton Tee", score: 72, cat: "Casual" },
      { name: "HEATTECH Ultra Warm", score: 32, cat: "Athletic" },
      { name: "AIRism Boxer Briefs", score: 35, cat: "Underwear" },
      { name: "Essential Tee", score: 68, cat: "Casual" },
    ]},
  { id: "hm", name: "H&M", score: 52, logo: "🏷️", tier: "moderate",
    summary: "Conscious Choice line scores better, but core line is fast fashion with chemical treatments. Inconsistent across products.",
    materials: ["Cotton", "Polyester", "Viscose"],
    certs: ["OEKO-TEX (select items)"],
    chemicals: ["formaldehyde", "antimony", "phthalates"], origin: "Bangladesh, China, Turkey",
    products: [
      { name: "Conscious Cotton Tee", score: 65, cat: "Casual" },
      { name: "Regular Fit Jeans", score: 58, cat: "Casual" },
      { name: "Sports Tights", score: 30, cat: "Athletic" },
    ]},
  { id: "gap", name: "Gap", score: 58, logo: "🇺🇸", tier: "moderate",
    summary: "Cotton-forward basics keep it moderate. Limited chemical transparency. Athleta sub-brand scores better.",
    materials: ["Cotton", "Cotton/Polyester blends"],
    certs: [],
    chemicals: ["formaldehyde"], origin: "Vietnam, China, India",
    products: [
      { name: "Classic Pocket Tee", score: 66, cat: "Casual" },
      { name: "Vintage Wash Jeans", score: 60, cat: "Casual" },
    ]},
  { id: "carhartt", name: "Carhartt", score: 58, logo: "🔨", tier: "moderate",
    summary: "Heavy cotton construction is a plus. But poly/cotton blends and stain-resistant treatments add chemical load.",
    materials: ["Cotton", "Cotton/Polyester", "Nylon"],
    certs: [],
    chemicals: ["formaldehyde", "antimony"], origin: "Multiple countries",
    products: [
      { name: "Pocket Tee", score: 66, cat: "Casual" },
      { name: "Fleece Hoodie", score: 55, cat: "Casual" },
      { name: "Rain Defender Jacket", score: 38, cat: "Outerwear" },
    ]},
  { id: "calvin_klein", name: "Calvin Klein", score: 55, logo: "🩲", tier: "moderate",
    summary: "Underwear line is mostly cotton (decent). Performance and athleisure lines shift to synthetics with higher chemical risk.",
    materials: ["Cotton", "Modal", "Polyester/Elastane"],
    certs: [],
    chemicals: ["formaldehyde", "phthalates"], origin: "Multiple countries",
    products: [
      { name: "Classic Boxer Brief", score: 62, cat: "Underwear" },
      { name: "Cotton Stretch Trunk", score: 64, cat: "Underwear" },
      { name: "Performance Tee", score: 36, cat: "Athletic" },
    ]},
  { id: "brooks_brothers", name: "Brooks Brothers", score: 64, logo: "👔", tier: "moderate",
    summary: "Traditional cotton and wool suiting scores well. Non-iron/wrinkle-free shirts use formaldehyde treatments.",
    materials: ["Cotton", "Wool", "Cotton/Polyester"],
    certs: [],
    chemicals: ["formaldehyde"], origin: "Multiple countries",
    products: [
      { name: "Classic Oxford Shirt", score: 70, cat: "Casual" },
      { name: "Non-Iron Dress Shirt", score: 48, cat: "Casual" },
      { name: "Wool Suit", score: 80, cat: "Casual" },
    ]},

  // ---- HIGH RISK TIER (0-44) ----
  { id: "nike", name: "Nike", score: 35, logo: "✓", tier: "high_risk",
    summary: "Dominant polyester/nylon/spandex across performance lines. Dri-FIT technology relies on synthetic chemical treatments. High chemical absorption during exercise.",
    materials: ["Polyester", "Nylon", "Spandex", "Recycled Polyester"],
    certs: ["bluesign (select)"],
    chemicals: ["antimony", "microplastics", "bpa", "phthalates"], origin: "Vietnam, China, Indonesia",
    products: [
      { name: "Dri-FIT Tee", score: 34, cat: "Athletic" },
      { name: "Tech Fleece Hoodie", score: 32, cat: "Athletic" },
      { name: "Pro Compression Tights", score: 26, cat: "Athletic" },
      { name: "Kids Dri-FIT Tee", score: 33, cat: "Kids" },
    ]},
  { id: "adidas", name: "Adidas", score: 37, logo: "⫼", tier: "high_risk",
    summary: "Heavily synthetic. Climalite and AEROREADY are polyester-based with chemical moisture management. Some Parley ocean plastic lines.",
    materials: ["Polyester", "Recycled Polyester", "Nylon/Elastane"],
    certs: [],
    chemicals: ["antimony", "microplastics", "bpa", "phthalates"], origin: "Vietnam, China, Indonesia",
    products: [
      { name: "AEROREADY Tee", score: 36, cat: "Athletic" },
      { name: "Ultraboost Running Shoe", score: 34, cat: "Athletic" },
      { name: "Tiro Track Pants", score: 33, cat: "Athletic" },
    ]},
  { id: "under_armour", name: "Under Armour", score: 32, logo: "🛡️", tier: "high_risk",
    summary: "Almost entirely synthetic performance fabrics. HeatGear and ColdGear are polyester/elastane with extensive chemical treatments.",
    materials: ["Polyester", "Elastane", "Nylon"],
    certs: [],
    chemicals: ["antimony", "microplastics", "bpa", "phthalates", "formaldehyde"], origin: "Jordan, China, Vietnam",
    products: [
      { name: "HeatGear Compression", score: 30, cat: "Athletic" },
      { name: "ColdGear Base Layer", score: 28, cat: "Athletic" },
      { name: "Tech 2.0 Tee", score: 33, cat: "Athletic" },
    ]},
  { id: "lululemon", name: "Lululemon", score: 31, logo: "🧘", tier: "high_risk",
    summary: "Premium price, but Nulu/Luon/Everlux fabrics are nylon-spandex blends. High skin contact during exercise increases chemical transfer rates.",
    materials: ["Nylon", "Lycra", "Polyester"],
    certs: [],
    chemicals: ["microplastics", "phthalates", "formaldehyde"], origin: "Vietnam, Cambodia, Sri Lanka",
    products: [
      { name: "Align Leggings", score: 29, cat: "Athletic" },
      { name: "Swiftly Tech Tee", score: 31, cat: "Athletic" },
      { name: "Wunder Train Leggings", score: 30, cat: "Athletic" },
    ]},
  { id: "gymshark", name: "Gymshark", score: 32, logo: "🦈", tier: "high_risk",
    summary: "Fast-growing but entirely synthetic. Polyester/nylon/elastane across all products. No certifications, limited transparency.",
    materials: ["Polyester", "Nylon", "Elastane"],
    certs: [],
    chemicals: ["antimony", "microplastics", "phthalates", "bpa"], origin: "China, Vietnam, Bangladesh",
    products: [
      { name: "Vital Seamless Tee", score: 32, cat: "Athletic" },
      { name: "Gym Shorts", score: 31, cat: "Athletic" },
      { name: "Instinct Shorts", score: 33, cat: "Athletic" },
    ]},
  { id: "2xu", name: "2XU", score: 28, logo: "🏋️", tier: "high_risk",
    summary: "Compression specialist — the tightest skin contact in the industry combined with fully synthetic materials. Maximum chemical transfer.",
    materials: ["Nylon", "Elastane", "Polyester"],
    certs: [],
    chemicals: ["microplastics", "phthalates", "formaldehyde", "bpa"], origin: "China",
    products: [
      { name: "Compression Tights", score: 28, cat: "Athletic" },
      { name: "Core Compression Shorts", score: 27, cat: "Athletic" },
    ]},
  { id: "victorias_secret", name: "Victoria's Secret", score: 34, logo: "💗", tier: "high_risk",
    summary: "Intimate apparel in nylon/polyester with high skin contact zones. Bras, underwear, and sleepwear all synthetic-heavy.",
    materials: ["Nylon", "Polyester", "Elastane"],
    certs: [],
    chemicals: ["microplastics", "phthalates", "formaldehyde"], origin: "Sri Lanka, Vietnam, China",
    products: [
      { name: "Seamless Thong", score: 35, cat: "Underwear" },
      { name: "Satin Pajamas", score: 38, cat: "Sleepwear" },
      { name: "Sports Bra", score: 28, cat: "Athletic" },
    ]},
  { id: "shein", name: "Shein", score: 18, logo: "⚡", tier: "high_risk",
    summary: "Lowest scores in database. Ultra-fast fashion with minimal quality control. Multiple independent test reports (Greenpeace Detox 2022, EWG textile testing) have documented elevated lead, PFAS, and formaldehyde levels in Shein products.",
    materials: ["Polyester", "Cotton/Polyester blends", "Acrylic"],
    certs: [],
    chemicals: ["antimony", "microplastics", "formaldehyde", "phthalates", "azo_dyes", "heavy_metals"], origin: "China",
    products: [
      { name: "Basic Crop Top", score: 18, cat: "Casual" },
      { name: "Workout Set", score: 15, cat: "Athletic" },
      { name: "Kids Graphic Tee", score: 16, cat: "Kids" },
    ]},
  { id: "temu", name: "Temu", score: 16, logo: "📦", tier: "high_risk",
    summary: "Unregulated marketplace. No quality oversight on chemical content. Products frequently fail safety testing in independent studies.",
    materials: ["Unknown synthetics", "Polyester blends"],
    certs: [],
    chemicals: ["antimony", "microplastics", "formaldehyde", "phthalates", "azo_dyes", "heavy_metals", "bpa"], origin: "China",
    products: [
      { name: "Generic Activewear Set", score: 14, cat: "Athletic" },
      { name: "Kids Clothing Pack", score: 12, cat: "Kids" },
    ]},
  { id: "fashion_nova", name: "Fashion Nova", score: 22, logo: "🌟", tier: "high_risk",
    summary: "Fast fashion with heavy synthetic content. Minimal ingredient/material disclosure. Targets young women with high-contact bodycon styles.",
    materials: ["Polyester", "Nylon", "Rayon"],
    certs: [],
    chemicals: ["antimony", "microplastics", "formaldehyde", "phthalates", "azo_dyes"], origin: "China, USA (some)",
    products: [
      { name: "Bodycon Dress", score: 20, cat: "Casual" },
      { name: "High Waist Leggings", score: 22, cat: "Athletic" },
    ]},
  { id: "boohoo", name: "Boohoo", score: 20, logo: "💅", tier: "high_risk",
    summary: "Ultra-fast fashion with documented supply chain issues. Synthetic-heavy, minimal safety testing disclosure.",
    materials: ["Polyester", "Viscose", "Nylon"],
    certs: [],
    chemicals: ["antimony", "microplastics", "formaldehyde", "phthalates", "azo_dyes"], origin: "UK, China, Bangladesh",
    products: [
      { name: "Mesh Bodysuit", score: 18, cat: "Casual" },
      { name: "Jersey Joggers", score: 25, cat: "Casual" },
    ]},

  // ---- MORE MODERATE ----
  { id: "north_face", name: "The North Face", score: 42, logo: "⛰️", tier: "high_risk",
    summary: "Outerwear relies on nylon and polyester with DWR coatings (PFAS risk). Some Futurelight items moving toward PFC-free.",
    materials: ["Nylon", "Polyester", "Gore-Tex"],
    certs: ["bluesign (select)"],
    chemicals: ["microplastics", "pfas", "formaldehyde"], origin: "Vietnam, China, Bangladesh",
    products: [
      { name: "Thermoball Jacket", score: 36, cat: "Outerwear" },
      { name: "Reaxion Tee", score: 34, cat: "Athletic" },
      { name: "Denali Fleece", score: 40, cat: "Outerwear" },
    ]},
  { id: "jcrew", name: "J.Crew", score: 68, logo: "⚓", tier: "moderate",
    summary: "Linen and cotton-heavy product lines score well. Some synthetic blends in performance and stretch items.",
    materials: ["Cotton", "Linen", "Wool", "Cotton/Polyester"],
    certs: [],
    chemicals: ["formaldehyde"], origin: "Multiple countries",
    products: [
      { name: "Linen Camp Shirt", score: 84, cat: "Casual" },
      { name: "Broken-in Tee", score: 68, cat: "Casual" },
      { name: "Wool Overcoat", score: 82, cat: "Outerwear" },
    ]},
  { id: "hanes", name: "Hanes", score: 60, logo: "📦", tier: "moderate",
    summary: "Cotton underwear and basics are decent. ComfortSoft line is mostly cotton. Performance lines shift to synthetics.",
    materials: ["Cotton", "Cotton/Polyester"],
    certs: [],
    chemicals: ["formaldehyde"], origin: "Honduras, El Salvador, USA",
    products: [
      { name: "ComfortSoft Tee", score: 66, cat: "Casual" },
      { name: "Cotton Boxer Briefs", score: 64, cat: "Underwear" },
      { name: "Cool DRI Tee", score: 34, cat: "Athletic" },
    ]},
  { id: "new_balance", name: "New Balance", score: 38, logo: "NB", tier: "high_risk",
    summary: "Athletic focus means synthetic-heavy. Some Made in USA products with better oversight, but core line is standard polyester/nylon.",
    materials: ["Polyester", "Nylon", "Mesh synthetics"],
    certs: [],
    chemicals: ["antimony", "microplastics", "phthalates"], origin: "USA (some), China, Vietnam",
    products: [
      { name: "Impact Run Tee", score: 36, cat: "Athletic" },
      { name: "Essentials Hoodie", score: 52, cat: "Casual" },
    ]},
  { id: "amazon_essentials", name: "Amazon Essentials", score: 50, logo: "📦", tier: "moderate",
    summary: "Budget basics. Cotton items are acceptable, but no certifications and minimal transparency on chemical treatments.",
    materials: ["Cotton", "Polyester", "Cotton/Polyester blends"],
    certs: [],
    chemicals: ["formaldehyde", "antimony"], origin: "Various",
    products: [
      { name: "Crewneck Tee 2-Pack", score: 58, cat: "Casual" },
      { name: "Performance Tee", score: 34, cat: "Athletic" },
    ]},
  { id: "vuori", name: "Vuori", score: 44, logo: "🌊", tier: "high_risk",
    summary: "Premium athleisure but still polyester/elastane core. Some recycled content. Better transparency than most athletic brands but same base materials.",
    materials: ["Recycled Polyester", "Elastane", "Nylon"],
    certs: [],
    chemicals: ["antimony", "microplastics", "phthalates"], origin: "China, Vietnam",
    products: [
      { name: "Strato Tech Tee", score: 42, cat: "Athletic" },
      { name: "Kore Shorts", score: 40, cat: "Athletic" },
    ]},


  // ──────── SAFE TIER (70-100) ────────
  { id: "eileen_fisher", name: "Eileen Fisher", score: 89, logo: "♻️", tier: "safe",
    summary: "Circular design pioneer. OEKO-TEX certified, organic linen and cotton, take-back program for all garments.",
    materials: ["Organic Cotton", "Organic Linen", "Tencel", "Recycled Cashmere"],
    certs: ["OEKO-TEX", "bluesign", "B Corp"],
    chemicals: [], origin: "China, USA, Peru",
    products: [
      { name: "Organic Cotton Crew", score: 91, cat: "Casual" },
      { name: "Tencel Wrap Dress", score: 87, cat: "Casual" },
      { name: "Organic Linen Pants", score: 90, cat: "Casual" },
    ]},
  { id: "tentree", name: "tentree", score: 86, logo: "🌳", tier: "safe",
    summary: "Plants 10 trees per item. Organic cotton, Tencel, recycled polyester. Strong transparency reporting.",
    materials: ["Organic Cotton", "Tencel", "Recycled Polyester", "Hemp"],
    certs: ["OEKO-TEX", "B Corp", "FSC"],
    chemicals: [], origin: "China, Vietnam, Bangladesh",
    products: [
      { name: "Classic Cotton Tee", score: 88, cat: "Casual" },
      { name: "French Terry Hoodie", score: 84, cat: "Casual" },
      { name: "Organic Joggers", score: 86, cat: "Casual" },
    ]},
  { id: "kotn", name: "Kotn", score: 88, logo: "🇪🇬", tier: "safe",
    summary: "Egyptian cotton direct from Nile Delta farms. Vertically integrated, no middlemen, GOTS certified.",
    materials: ["Egyptian Cotton", "Organic Cotton"],
    certs: ["GOTS", "B Corp"],
    chemicals: [], origin: "Egypt, Portugal",
    products: [
      { name: "Essential Crew Tee", score: 90, cat: "Casual" },
      { name: "Oxford Button-Down", score: 88, cat: "Casual" },
      { name: "Classic Hoodie", score: 85, cat: "Casual" },
    ]},
  { id: "mate_the_label", name: "MATE the Label", score: 90, logo: "🌱", tier: "safe",
    summary: "Certified organic, made in LA. No chemical classes flagged at MEDIUM or HIGH confidence under V3 methodology. GOTS-certified organic cotton; OEKO-TEX Standard 100 verified.",
    materials: ["Organic Cotton", "Organic Linen"],
    certs: ["GOTS", "OEKO-TEX"],
    chemicals: [], origin: "USA",
    products: [
      { name: "Classic Crew", score: 92, cat: "Casual" },
      { name: "Organic Biker Short", score: 89, cat: "Athletic" },
      { name: "Organic Tank", score: 91, cat: "Casual" },
    ]},
  { id: "colorful_standard", name: "Colorful Standard", score: 87, logo: "🎨", tier: "safe",
    summary: "100% organic cotton basics. OEKO-TEX certified, low-impact dyes, simple supply chain.",
    materials: ["Organic Cotton"],
    certs: ["GOTS", "OEKO-TEX"],
    chemicals: [], origin: "Portugal",
    products: [
      { name: "Classic Organic Tee", score: 89, cat: "Casual" },
      { name: "Organic Hoodie", score: 86, cat: "Casual" },
      { name: "Organic Sweatshirt", score: 87, cat: "Casual" },
    ]},
  { id: "thought", name: "Thought Clothing", score: 85, logo: "🧶", tier: "safe",
    summary: "Bamboo, hemp, organic cotton focus. OEKO-TEX certified, natural dyes on many lines.",
    materials: ["Bamboo", "Hemp", "Organic Cotton", "Wool"],
    certs: ["OEKO-TEX", "GOTS"],
    chemicals: [], origin: "China, India",
    products: [
      { name: "Hemp Crew Tee", score: 88, cat: "Casual" },
      { name: "Bamboo Ankle Socks", score: 84, cat: "Underwear" },
      { name: "Organic Midi Dress", score: 83, cat: "Casual" },
    ]},
  { id: "organic_basics", name: "Organic Basics", score: 91, logo: "🍃", tier: "safe",
    summary: "Certified organic across all products. SilverTech antimicrobial line uses recycled silver, not chemical treatments.",
    materials: ["Organic Cotton", "Tencel", "Recycled Nylon", "Organic Wool"],
    certs: ["GOTS", "OEKO-TEX", "GRS"],
    chemicals: [], origin: "Portugal, Turkey",
    products: [
      { name: "Organic Cotton Boxers", score: 93, cat: "Underwear" },
      { name: "Organic Bralette", score: 92, cat: "Underwear" },
      { name: "Tencel Tee", score: 89, cat: "Casual" },
      { name: "SilverTech Active Tee", score: 85, cat: "Athletic" },
    ]},
  { id: "nudie_jeans", name: "Nudie Jeans", score: 84, logo: "👖", tier: "safe",
    summary: "100% organic cotton denim. Free repairs forever. GOTS certified, transparent supply chain.",
    materials: ["Organic Cotton", "Recycled Cotton"],
    certs: ["GOTS", "Fair Trade"],
    chemicals: [], origin: "Italy, Tunisia, Turkey",
    products: [
      { name: "Lean Dean Jeans", score: 86, cat: "Casual" },
      { name: "Steady Eddie II", score: 85, cat: "Casual" },
      { name: "Organic Crew Tee", score: 88, cat: "Casual" },
    ]},
  { id: "wolford", name: "Wolford", score: 78, logo: "🩲", tier: "safe",
    summary: "OEKO-TEX Standard 100 certified. Austrian made. High-quality nylon/elastane but certified chemical-safe.",
    materials: ["Nylon", "Elastane", "Cotton"],
    certs: ["OEKO-TEX"],
    chemicals: ["microplastics"], origin: "Austria, Slovenia",
    products: [
      { name: "Pure Tee", score: 80, cat: "Casual" },
      { name: "Cotton Contour Bra", score: 75, cat: "Underwear" },
    ]},
  { id: "veja", name: "VEJA", score: 82, logo: "👟", tier: "safe",
    summary: "Wild rubber soles, organic cotton canvas, chromium-free leather. Transparent sourcing from Brazil.",
    materials: ["Organic Cotton", "Wild Rubber", "Chromium-Free Leather"],
    certs: ["B Corp"],
    chemicals: [], origin: "Brazil",
    products: [
      { name: "Campo Canvas Sneaker", score: 83, cat: "Casual" },
      { name: "V-10 Leather Sneaker", score: 78, cat: "Casual" },
    ]},

  // ──────── MODERATE TIER (45-69) ────────
  { id: "everlane", name: "Everlane", score: 65, logo: "🏷️", tier: "moderate",
    summary: "Radical transparency on pricing and factories. Conventional cotton with some organic. Better than fast fashion but not certified.",
    materials: ["Cotton", "Organic Cotton", "Recycled Polyester", "Cashmere"],
    certs: [],
    chemicals: ["formaldehyde"], origin: "China, Vietnam, Italy",
    products: [
      { name: "Essential Organic Tee", score: 78, cat: "Casual" },
      { name: "The Performance Chino", score: 52, cat: "Casual" },
      { name: "ReNew Puffer", score: 48, cat: "Outerwear" },
      { name: "The Dream Pant", score: 56, cat: "Casual" },
    ]},
  { id: "asos", name: "ASOS", score: 38, logo: "🛒", tier: "high_risk",
    summary: "Massive fast fashion marketplace. Some sustainable sub-lines (ASOS Design) but bulk is conventional synthetic.",
    materials: ["Polyester", "Cotton", "Viscose", "Nylon"],
    certs: [],
    chemicals: ["formaldehyde", "azo_dyes", "phthalates"], origin: "China, Bangladesh, Turkey",
    products: [
      { name: "Muscle Fit Tee", score: 35, cat: "Casual" },
      { name: "Skinny Jeans", score: 42, cat: "Casual" },
      { name: "Running Shorts", score: 30, cat: "Athletic" },
    ]},
  { id: "champion", name: "Champion", score: 50, logo: "🏆", tier: "moderate",
    summary: "Heritage athletic brand. Cotton-heavy basics score well but synthetic performance gear has typical chemical issues.",
    materials: ["Cotton", "Polyester", "Cotton/Polyester Blend"],
    certs: [],
    chemicals: ["formaldehyde", "antimony"], origin: "Honduras, Vietnam, China",
    products: [
      { name: "Classic Cotton Tee", score: 62, cat: "Casual" },
      { name: "Reverse Weave Hoodie", score: 58, cat: "Casual" },
      { name: "Double Dry Performance Tee", score: 35, cat: "Athletic" },
    ]},
  { id: "old_navy", name: "Old Navy", score: 45, logo: "⚓", tier: "moderate",
    summary: "Gap subsidiary, budget-focused. Conventional cotton and polyester blends. Some organic options but majority is treated.",
    materials: ["Cotton", "Polyester", "Spandex", "Rayon"],
    certs: [],
    chemicals: ["formaldehyde", "phthalates"], origin: "Bangladesh, Vietnam, China",
    products: [
      { name: "Softest Crew-Neck Tee", score: 52, cat: "Casual" },
      { name: "Active Powersoft Leggings", score: 32, cat: "Athletic" },
      { name: "Cotton Boxer Briefs", score: 48, cat: "Underwear" },
    ]},
  { id: "columbia", name: "Columbia Sportswear", score: 52, logo: "⛰️", tier: "moderate",
    summary: "Omni-Heat and Omni-Shade technologies rely on chemical coatings. Some bluesign products. Mixed chemical profile.",
    materials: ["Polyester", "Nylon", "Cotton"],
    certs: ["bluesign (select)"],
    chemicals: ["antimony", "pfas", "microplastics"], origin: "Vietnam, Bangladesh, China",
    products: [
      { name: "PFG Fishing Shirt", score: 45, cat: "Casual" },
      { name: "Silver Ridge Hiking Shirt", score: 50, cat: "Athletic" },
      { name: "Omni-Heat Base Layer", score: 38, cat: "Athletic" },
      { name: "Benton Springs Fleece", score: 42, cat: "Outerwear" },
    ]},
  { id: "ralph_lauren", name: "Ralph Lauren", score: 56, logo: "🐴", tier: "moderate",
    summary: "Luxury casual. Conventional cotton polos, some organic options. Better manufacturing oversight than fast fashion.",
    materials: ["Cotton", "Wool", "Cashmere", "Polyester"],
    certs: [],
    chemicals: ["formaldehyde"], origin: "China, Vietnam, Italy, Sri Lanka",
    products: [
      { name: "Classic Fit Polo", score: 58, cat: "Casual" },
      { name: "Cable-Knit Cotton Sweater", score: 55, cat: "Casual" },
      { name: "Performance Polo", score: 40, cat: "Athletic" },
    ]},
  { id: "tommy_hilfiger", name: "Tommy Hilfiger", score: 52, logo: "🇺🇸", tier: "moderate",
    summary: "PVH Corp brand. Some sustainable initiatives but conventional materials dominate. OEKO-TEX on select items.",
    materials: ["Cotton", "Polyester", "Elastane"],
    certs: ["OEKO-TEX (select)"],
    chemicals: ["formaldehyde", "phthalates"], origin: "Bangladesh, China, India",
    products: [
      { name: "Essential Cotton Tee", score: 55, cat: "Casual" },
      { name: "Flag Logo Hoodie", score: 50, cat: "Casual" },
      { name: "Boxer Briefs 3-Pack", score: 48, cat: "Underwear" },
    ]},
  { id: "banana_republic", name: "Banana Republic", score: 55, logo: "🍌", tier: "moderate",
    summary: "Gap's premium line. Better materials than Old Navy, some silk and cashmere. Factory transparency improving.",
    materials: ["Cotton", "Silk", "Wool", "Cashmere", "Polyester"],
    certs: [],
    chemicals: ["formaldehyde"], origin: "China, Vietnam, Italy",
    products: [
      { name: "Luxury-Touch Cotton Tee", score: 58, cat: "Casual" },
      { name: "Merino Wool Sweater", score: 68, cat: "Casual" },
      { name: "Italian Wool Suit", score: 62, cat: "Casual" },
    ]},
  { id: "reebok", name: "Reebok", score: 42, logo: "🔺", tier: "high_risk",
    summary: "Now Authentic Brands Group. Polyester-dominant performance line. Same chemical profile as Nike/Adidas synthetic gear.",
    materials: ["Polyester", "Nylon", "Spandex"],
    certs: [],
    chemicals: ["antimony", "bpa", "microplastics", "formaldehyde"], origin: "Vietnam, China, Indonesia",
    products: [
      { name: "Workout Ready Tee", score: 38, cat: "Athletic" },
      { name: "Nano X Training Shoe", score: 35, cat: "Athletic" },
      { name: "Classic Nylon Sneaker", score: 42, cat: "Casual" },
    ]},
  { id: "asics", name: "ASICS", score: 45, logo: "🏃", tier: "moderate",
    summary: "Performance running brand. Some recycled materials. Chemical treatments for moisture management.",
    materials: ["Polyester", "Recycled Polyester", "Nylon"],
    certs: ["OEKO-TEX (select)"],
    chemicals: ["antimony", "microplastics"], origin: "Vietnam, Indonesia, China",
    products: [
      { name: "Gel-Kayano Running Shoe", score: 42, cat: "Athletic" },
      { name: "Core Running Tee", score: 44, cat: "Athletic" },
      { name: "Sport Running Shorts", score: 40, cat: "Athletic" },
    ]},
  { id: "puma", name: "Puma", score: 48, logo: "🐆", tier: "moderate",
    summary: "Committed to eliminating hazardous chemicals by 2025. Better transparency than most, but still polyester-heavy.",
    materials: ["Polyester", "Recycled Polyester", "Cotton", "Nylon"],
    certs: ["OEKO-TEX (select)"],
    chemicals: ["antimony", "microplastics", "formaldehyde"], origin: "Vietnam, China, Bangladesh",
    products: [
      { name: "Essentials Cotton Tee", score: 58, cat: "Casual" },
      { name: "Run Favorite Tee", score: 38, cat: "Athletic" },
      { name: "Cloudspun Golf Polo", score: 42, cat: "Athletic" },
    ]},
  { id: "nordstrom", name: "Nordstrom (House Brand)", score: 55, logo: "🏬", tier: "moderate",
    summary: "Department store brand. Quality varies by line. BP and Treasure & Bond are conventional, Caslon slightly better.",
    materials: ["Cotton", "Polyester", "Viscose", "Wool"],
    certs: [],
    chemicals: ["formaldehyde", "phthalates"], origin: "China, Vietnam, India",
    products: [
      { name: "Cotton Blend Crewneck", score: 55, cat: "Casual" },
      { name: "Everyday Cotton Tee", score: 58, cat: "Casual" },
    ]},
  { id: "brooks_running", name: "Brooks Running", score: 50, logo: "🏃‍♂️", tier: "moderate",
    summary: "Running-focused brand. DriLayer fabrics are polyester-based. B Corp certified but synthetic-heavy.",
    materials: ["Polyester", "Recycled Polyester", "Nylon", "Elastane"],
    certs: ["B Corp"],
    chemicals: ["antimony", "microplastics"], origin: "Vietnam, China",
    products: [
      { name: "Ghost Running Shoe", score: 45, cat: "Athletic" },
      { name: "Sherpa Half-Zip", score: 48, cat: "Athletic" },
      { name: "Momentum Thermal Tights", score: 38, cat: "Athletic" },
    ]},
  { id: "reformation", name: "Reformation", score: 68, logo: "🌸", tier: "moderate",
    summary: "Trendy sustainable brand. Tencel-heavy, deadstock fabrics. Good transparency but not fully certified organic.",
    materials: ["Tencel", "Recycled Cotton", "Linen", "Deadstock Fabrics"],
    certs: ["Climate Neutral"],
    chemicals: [], origin: "USA, China",
    products: [
      { name: "Classic Crew Tee", score: 72, cat: "Casual" },
      { name: "Linen Midi Dress", score: 75, cat: "Casual" },
      { name: "Tencel Wrap Top", score: 70, cat: "Casual" },
    ]},
  { id: "athleta", name: "Athleta", score: 55, logo: "🧘", tier: "moderate",
    summary: "Gap's athletic brand. Nylon/lycra core like Lululemon. B Corp certified, some recycled content. Better intent, similar materials.",
    materials: ["Nylon", "Lycra", "Recycled Polyester", "Organic Cotton"],
    certs: ["B Corp"],
    chemicals: ["microplastics", "phthalates"], origin: "Vietnam, Sri Lanka, China",
    products: [
      { name: "Elation Tight", score: 38, cat: "Athletic" },
      { name: "Organic Daily Tank", score: 72, cat: "Casual" },
      { name: "Conscious Crop", score: 45, cat: "Athletic" },
    ]},
  { id: "on_running", name: "On Running", score: 48, logo: "☁️", tier: "moderate",
    summary: "Swiss performance brand. CloudTec foam and polyester uppers. Some recycled materials. Chemical profile typical of performance footwear.",
    materials: ["Recycled Polyester", "Polyester", "EVA Foam"],
    certs: [],
    chemicals: ["antimony", "microplastics"], origin: "Vietnam, Indonesia",
    products: [
      { name: "Cloud 5 Running Shoe", score: 44, cat: "Athletic" },
      { name: "Performance-T", score: 42, cat: "Athletic" },
      { name: "Running Shorts", score: 40, cat: "Athletic" },
    ]},

  // ──────── HIGH RISK TIER (0-44) ────────
  { id: "zara", name: "Zara", score: 38, logo: "🏪", tier: "high_risk",
    summary: "World's largest fast fashion retailer. Rapid turnover, conventional treatments. Join Life sub-line is slightly better.",
    materials: ["Polyester", "Cotton", "Viscose", "Acrylic"],
    certs: [],
    chemicals: ["formaldehyde", "azo_dyes", "phthalates", "antimony"], origin: "Bangladesh, Turkey, China, Morocco",
    products: [
      { name: "Basic Crew Neck Tee", score: 42, cat: "Casual" },
      { name: "Technical Running Tee", score: 30, cat: "Athletic" },
      { name: "Skinny Jeans", score: 38, cat: "Casual" },
      { name: "Puffer Jacket", score: 28, cat: "Outerwear" },
    ]},
  { id: "primark", name: "Primark", score: 30, logo: "💷", tier: "high_risk",
    summary: "Ultra-budget fast fashion. Extremely high volume, minimal chemical oversight. Penneys in Ireland.",
    materials: ["Polyester", "Cotton", "Acrylic", "Viscose"],
    certs: [],
    chemicals: ["formaldehyde", "azo_dyes", "heavy_metals", "phthalates"], origin: "Bangladesh, China, India",
    products: [
      { name: "Basic Cotton Tee", score: 35, cat: "Casual" },
      { name: "Active Leggings", score: 22, cat: "Athletic" },
      { name: "Fleece Hoodie", score: 28, cat: "Casual" },
    ]},
  { id: "forever21", name: "Forever 21", score: 28, logo: "💛", tier: "high_risk",
    summary: "Ultra-fast fashion, minimal transparency. Frequent chemical testing failures in independent studies.",
    materials: ["Polyester", "Rayon", "Nylon", "Acrylic"],
    certs: [],
    chemicals: ["formaldehyde", "azo_dyes", "heavy_metals", "phthalates", "pfas"], origin: "China, Bangladesh, Vietnam",
    products: [
      { name: "Crop Top", score: 25, cat: "Casual" },
      { name: "Athletic Leggings", score: 22, cat: "Athletic" },
      { name: "Faux Leather Jacket", score: 18, cat: "Outerwear" },
    ]},
  { id: "romwe", name: "ROMWE", score: 15, logo: "📦", tier: "high_risk",
    summary: "Shein subsidiary. Same supply chain, same issues. Ultra-cheap, zero transparency.",
    materials: ["Polyester", "Spandex", "Acrylic"],
    certs: [],
    chemicals: ["formaldehyde", "azo_dyes", "heavy_metals", "phthalates", "bpa", "pfas"], origin: "China",
    products: [
      { name: "Graphic Tee", score: 18, cat: "Casual" },
      { name: "Workout Set", score: 12, cat: "Athletic" },
    ]},
  { id: "plt", name: "PrettyLittleThing", score: 25, logo: "💅", tier: "high_risk",
    summary: "Boohoo subsidiary. Ultra-fast fashion. UK investigations found worker exploitation and chemical safety issues.",
    materials: ["Polyester", "Nylon", "Viscose", "Acrylic"],
    certs: [],
    chemicals: ["formaldehyde", "azo_dyes", "phthalates", "heavy_metals"], origin: "UK (Leicester), China, Bangladesh",
    products: [
      { name: "Bodycon Dress", score: 22, cat: "Casual" },
      { name: "Gym Leggings", score: 20, cat: "Athletic" },
      { name: "Oversized Tee", score: 28, cat: "Casual" },
    ]},
  { id: "missguided", name: "Missguided", score: 26, logo: "💜", tier: "high_risk",
    summary: "Fast fashion, now owned by Frasers Group. Minimal chemical transparency. Polyester-heavy.",
    materials: ["Polyester", "Viscose", "Nylon"],
    certs: [],
    chemicals: ["formaldehyde", "azo_dyes", "phthalates"], origin: "China, UK",
    products: [
      { name: "Basic Bodysuit", score: 24, cat: "Casual" },
      { name: "Jogger Set", score: 28, cat: "Casual" },
    ]},
  { id: "fabletics", name: "Fabletics", score: 36, logo: "🏋️", tier: "high_risk",
    summary: "Kate Hudson's athleisure brand. Nylon/spandex core. Subscription model pushes volume over quality. Same chemical profile as most synthetic activewear.",
    materials: ["Nylon", "Polyester", "Spandex"],
    certs: [],
    chemicals: ["antimony", "microplastics", "phthalates", "bpa"], origin: "China, Vietnam",
    products: [
      { name: "Define High-Waisted Legging", score: 32, cat: "Athletic" },
      { name: "The Everything Tank", score: 38, cat: "Athletic" },
      { name: "Sports Bra", score: 28, cat: "Underwear" },
    ]},
  { id: "target_brand", name: "Target (All in Motion / Cat & Jack)", score: 48, logo: "🎯", tier: "moderate",
    summary: "Target house brands. All in Motion athletic gear is polyester-heavy. Cat & Jack has OEKO-TEX on kids items.",
    materials: ["Polyester", "Cotton", "Spandex", "Recycled Polyester"],
    certs: ["OEKO-TEX (Cat & Jack)"],
    chemicals: ["antimony", "formaldehyde"], origin: "Bangladesh, China, Vietnam",
    products: [
      { name: "All in Motion Training Tee", score: 38, cat: "Athletic" },
      { name: "Goodfellow Cotton Tee", score: 58, cat: "Casual" },
      { name: "Cat & Jack Kids Tee", score: 62, cat: "Casual" },
    ]},
  { id: "walmart_brand", name: "Walmart (George / Athletic Works)", score: 35, logo: "🏪", tier: "high_risk",
    summary: "Walmart house brands. Price-first manufacturing. Minimal chemical oversight or certifications.",
    materials: ["Polyester", "Cotton", "Acrylic"],
    certs: [],
    chemicals: ["formaldehyde", "antimony", "phthalates", "azo_dyes"], origin: "Bangladesh, China, Honduras",
    products: [
      { name: "Athletic Works Training Tee", score: 30, cat: "Athletic" },
      { name: "George Cotton Polo", score: 45, cat: "Casual" },
      { name: "Athletic Works Shorts", score: 28, cat: "Athletic" },
    ]},
  { id: "costco_brand", name: "Kirkland Signature (Costco)", score: 52, logo: "🏷️", tier: "moderate",
    summary: "Better quality control than most house brands. Pima cotton basics score well. Athletic gear still synthetic-heavy.",
    materials: ["Cotton", "Pima Cotton", "Polyester", "Wool"],
    certs: [],
    chemicals: ["formaldehyde", "antimony"], origin: "Peru, China, Vietnam",
    products: [
      { name: "Pima Cotton Tee", score: 65, cat: "Casual" },
      { name: "Merino Wool Socks", score: 72, cat: "Underwear" },
      { name: "Performance Quarter-Zip", score: 38, cat: "Athletic" },
    ]},
  { id: "skechers", name: "Skechers", score: 38, logo: "💎", tier: "high_risk",
    summary: "Budget athletic/casual. Memory foam uses chemical propellants. Synthetic uppers with standard chemical treatments.",
    materials: ["Polyester", "Nylon", "Synthetic Leather", "EVA Foam"],
    certs: [],
    chemicals: ["antimony", "formaldehyde", "phthalates"], origin: "China, Vietnam",
    products: [
      { name: "GOwalk Slip-On", score: 35, cat: "Athletic" },
      { name: "Sport Mesh Sneaker", score: 32, cat: "Athletic" },
    ]},
  { id: "hollister", name: "Hollister", score: 42, logo: "🌴", tier: "high_risk",
    summary: "Abercrombie & Fitch subsidiary targeting teens. Conventional cotton/polyester. Fragrance spraying in stores adds chemical exposure.",
    materials: ["Cotton", "Polyester", "Viscose"],
    certs: [],
    chemicals: ["formaldehyde", "phthalates"], origin: "China, Vietnam, Bangladesh",
    products: [
      { name: "Must-Have Cotton Tee", score: 50, cat: "Casual" },
      { name: "Gilly Hicks Bralette", score: 35, cat: "Underwear" },
      { name: "Athletic Joggers", score: 38, cat: "Athletic" },
    ]},
  { id: "abercrombie", name: "Abercrombie & Fitch", score: 48, logo: "🦌", tier: "moderate",
    summary: "Improving sustainability commitments. Some OEKO-TEX items. Still predominantly conventional materials.",
    materials: ["Cotton", "Polyester", "Linen", "Viscose"],
    certs: ["OEKO-TEX (select)"],
    chemicals: ["formaldehyde", "phthalates"], origin: "China, Vietnam, Indonesia",
    products: [
      { name: "Essential Cotton Tee", score: 52, cat: "Casual" },
      { name: "Curve Love Jeans", score: 48, cat: "Casual" },
      { name: "YPB motionTEK Legging", score: 36, cat: "Athletic" },
    ]},
  { id: "american_eagle", name: "American Eagle", score: 46, logo: "🦅", tier: "moderate",
    summary: "Denim-focused brand. Real Good collection uses sustainable materials. Aerie line has improved but is still synthetic-heavy.",
    materials: ["Cotton", "Polyester", "Spandex", "Recycled Polyester"],
    certs: [],
    chemicals: ["formaldehyde", "phthalates"], origin: "China, Vietnam, Bangladesh",
    products: [
      { name: "Real Good Tee", score: 58, cat: "Casual" },
      { name: "AirFlex Jeans", score: 46, cat: "Casual" },
      { name: "Aerie Sports Bra", score: 32, cat: "Underwear" },
    ]},
  { id: "fruit_of_the_loom", name: "Fruit of the Loom", score: 42, logo: "🍇", tier: "high_risk",
    summary: "Basic underwear and tees. Conventional cotton with chemical sizing agents. Budget manufacturing.",
    materials: ["Cotton", "Polyester", "Cotton/Polyester Blend"],
    certs: [],
    chemicals: ["formaldehyde", "phthalates"], origin: "Honduras, El Salvador",
    products: [
      { name: "Classic Cotton Tee 5-Pack", score: 48, cat: "Casual" },
      { name: "Cotton Boxer Briefs", score: 45, cat: "Underwear" },
      { name: "EverSoft Cotton Tee", score: 50, cat: "Casual" },
    ]},
  { id: "gildan", name: "Gildan", score: 44, logo: "🏭", tier: "high_risk",
    summary: "World's largest blank tee manufacturer. Conventional cotton with standard chemical treatments. Supplies most screen printers.",
    materials: ["Cotton", "Cotton/Polyester Blend", "Polyester"],
    certs: [],
    chemicals: ["formaldehyde", "phthalates"], origin: "Honduras, Bangladesh, Nicaragua",
    products: [
      { name: "Heavy Cotton Tee", score: 48, cat: "Casual" },
      { name: "DryBlend Performance Tee", score: 34, cat: "Athletic" },
      { name: "Softstyle Cotton Tee", score: 50, cat: "Casual" },
    ]},
  { id: "next_level", name: "Next Level Apparel", score: 50, logo: "📐", tier: "moderate",
    summary: "Premium blank tees. Combed and ring-spun cotton scores better than Gildan. Popular with custom printers.",
    materials: ["Combed Cotton", "Cotton/Polyester Blend", "Tri-Blend"],
    certs: [],
    chemicals: ["formaldehyde"], origin: "Honduras, Nicaragua",
    products: [
      { name: "CVC Crew Tee", score: 55, cat: "Casual" },
      { name: "Premium Cotton Tee", score: 58, cat: "Casual" },
      { name: "Tri-Blend Tee", score: 42, cat: "Casual" },
    ]},
  { id: "alo_yoga", name: "Alo Yoga", score: 40, logo: "🧘‍♀️", tier: "high_risk",
    summary: "Premium yoga brand. Looks clean but uses nylon/polyester/spandex across most lines. Price premium doesn't mean chemical-safe.",
    materials: ["Nylon", "Polyester", "Spandex"],
    certs: [],
    chemicals: ["antimony", "microplastics", "phthalates", "bpa"], origin: "China, Vietnam",
    products: [
      { name: "Airlift High-Waist Legging", score: 35, cat: "Athletic" },
      { name: "Alosoft Crop Tank", score: 38, cat: "Athletic" },
      { name: "Accolade Hoodie", score: 42, cat: "Casual" },
    ]},
];

// ============================================================
// Brand Safety Data Layer — sourced from public records
// NRDC PFAS Scorecard 2023, Good On You, OEKO-TEX registry
// ============================================================
const BRAND_SAFETY_DATA = {
  levis:            { nrdc_pfas_rating: "A+", oeko_tex_certified: false, good_on_you_rating: "it's a start", confidence_tier: 2, data_sources: [{ name: "NRDC PFAS Brand Scorecard", url: "https://www.nrdc.org/press-releases/new-pfas-scorecard-popular-apparel-brands-levi-strauss-earns-outdoor-brands-fail", year: 2023 }] },
  nike:             { nrdc_pfas_rating: "B",  oeko_tex_certified: false, good_on_you_rating: "it's a start", confidence_tier: 2, data_sources: [{ name: "NRDC PFAS Brand Scorecard", url: "https://www.nrdc.org/press-releases/new-pfas-scorecard-popular-apparel-brands-levi-strauss-earns-outdoor-brands-fail", year: 2023 }, { name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  adidas:           { nrdc_pfas_rating: "B",  oeko_tex_certified: false, good_on_you_rating: "it's a start", confidence_tier: 2, data_sources: [{ name: "NRDC PFAS Brand Scorecard", url: "https://www.nrdc.org/press-releases/new-pfas-scorecard-popular-apparel-brands-levi-strauss-earns-outdoor-brands-fail", year: 2023 }, { name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  columbia:         { nrdc_pfas_rating: "F",  oeko_tex_certified: false, good_on_you_rating: null, confidence_tier: 2, data_sources: [{ name: "NRDC PFAS Brand Scorecard", url: "https://www.nrdc.org/press-releases/new-pfas-scorecard-popular-apparel-brands-levi-strauss-earns-outdoor-brands-fail", year: 2023 }] },
  patagonia:        { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "great", gots_certified: true, bluesign_certified: true, confidence_tier: 2, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  hm:               { nrdc_pfas_rating: null,  oeko_tex_certified: true,  good_on_you_rating: "it's a start", confidence_tier: 3, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  shein:            { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "we avoid", confidence_tier: 3, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  pact:             { nrdc_pfas_rating: null,  oeko_tex_certified: true,  good_on_you_rating: "great", gots_certified: true, confidence_tier: 2, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }, { name: "GOTS Registry", url: "https://global-standard.org", year: 2024 }] },
  smartwool:        { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "good", bluesign_certified: true, confidence_tier: 2, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  allbirds:         { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "great", confidence_tier: 2, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  coyuchi:          { nrdc_pfas_rating: null,  oeko_tex_certified: true,  good_on_you_rating: "great", gots_certified: true, confidence_tier: 2, data_sources: [{ name: "GOTS Registry", url: "https://global-standard.org", year: 2024 }] },
  under_armour:     { nrdc_pfas_rating: "D",  oeko_tex_certified: false, good_on_you_rating: "not good enough", confidence_tier: 2, data_sources: [{ name: "NRDC PFAS Brand Scorecard", url: "https://www.nrdc.org/press-releases/new-pfas-scorecard-popular-apparel-brands-levi-strauss-earns-outdoor-brands-fail", year: 2023 }] },
  lululemon:        { nrdc_pfas_rating: "C",  oeko_tex_certified: false, good_on_you_rating: "it's a start", confidence_tier: 2, data_sources: [{ name: "NRDC PFAS Brand Scorecard", url: "https://www.nrdc.org/press-releases/new-pfas-scorecard-popular-apparel-brands-levi-strauss-earns-outdoor-brands-fail", year: 2023 }] },
  north_face:       { nrdc_pfas_rating: "F",  oeko_tex_certified: false, good_on_you_rating: "it's a start", bluesign_certified: true, confidence_tier: 2, data_sources: [{ name: "NRDC PFAS Brand Scorecard", url: "https://www.nrdc.org/press-releases/new-pfas-scorecard-popular-apparel-brands-levi-strauss-earns-outdoor-brands-fail", year: 2023 }] },
  temu:             { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "we avoid", confidence_tier: 3, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  fashion_nova:     { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "we avoid", confidence_tier: 3, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  boohoo:           { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "we avoid", confidence_tier: 3, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  eileen_fisher:    { nrdc_pfas_rating: null,  oeko_tex_certified: true,  good_on_you_rating: "great", bluesign_certified: true, confidence_tier: 2, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }, { name: "OEKO-TEX Label Check", url: "https://www.oeko-tex.com/en/label-check", year: 2024 }] },
  tentree:          { nrdc_pfas_rating: null,  oeko_tex_certified: true,  good_on_you_rating: "great", confidence_tier: 2, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  kotn:             { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "great", gots_certified: true, confidence_tier: 2, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  mate_the_label:   { nrdc_pfas_rating: null,  oeko_tex_certified: true,  good_on_you_rating: "great", gots_certified: true, confidence_tier: 2, data_sources: [{ name: "GOTS Registry", url: "https://global-standard.org", year: 2024 }] },
  organic_basics:   { nrdc_pfas_rating: null,  oeko_tex_certified: true,  good_on_you_rating: "great", gots_certified: true, confidence_tier: 2, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  gymshark:         { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "not good enough", confidence_tier: 3, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  asos:             { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "it's a start", confidence_tier: 3, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  uniqlo:           { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "it's a start", confidence_tier: 3, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  gap:              { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "it's a start", confidence_tier: 3, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  everlane:         { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "good", confidence_tier: 3, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  victorias_secret: { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: "not good enough", confidence_tier: 3, data_sources: [{ name: "Good On You", url: "https://goodonyou.eco", year: 2024 }] },
  "2xu":            { nrdc_pfas_rating: null,  oeko_tex_certified: false, good_on_you_rating: null, confidence_tier: 4, data_sources: [] },
};

// Merge safety data into brand records
BRANDS.forEach(b => {
  const safety = BRAND_SAFETY_DATA[b.id];
  if (safety) {
    b.nrdc_pfas_rating = safety.nrdc_pfas_rating || null;
    b.oeko_tex_certified = safety.oeko_tex_certified || false;
    b.good_on_you_rating = safety.good_on_you_rating || null;
    b.gots_certified = safety.gots_certified || false;
    b.bluesign_certified = safety.bluesign_certified || false;
    b.prop65_violations = safety.prop65_violations || [];
    b.confidence_tier = safety.confidence_tier || 3;
    b.data_sources = safety.data_sources || [];
  } else {
    // No public source data — derive cert booleans from brand certs array
    const certsLower = (b.certs || []).map(c => c.toLowerCase());
    b.nrdc_pfas_rating = null;
    b.oeko_tex_certified = certsLower.some(c => c.includes("oeko"));
    b.good_on_you_rating = null;
    b.gots_certified = certsLower.some(c => c.includes("gots"));
    b.bluesign_certified = certsLower.some(c => c.includes("bluesign"));
    b.prop65_violations = [];
    // If brand has any recognized certs, tier 3 so brand score component is used
    b.confidence_tier = (b.oeko_tex_certified || b.gots_certified || b.bluesign_certified) ? 3 : 4;
    b.data_sources = [];
  }
  b.brand_name = b.name; // alias for scoring engine compatibility
});

// ── Re-score every product through the citation-based scoring engine ──
// This replaces all hardcoded scores with engine-computed values.
BRANDS.forEach(b => {
  b.products.forEach(p => {
    // Build a product object the scoring engine understands.
    // Include product name in materials so keywords like "Dri-FIT",
    // "Gore-Tex", "Non-Iron" trigger the right REACH flags.
    const materialStr = (b.materials || []).join(", ") + " " + (p.name || "");
    const productForEngine = {
      category: p.cat,
      materials: materialStr,
    };
    const result = engineScore(productForEngine, b);
    if (result) {
      p.score = result.score;
      p.v2 = result;
    }
    // If engine returns null (no data at all), keep existing hardcoded score
  });

  // Recompute brand-level score as average of its products
  if (b.products.length > 0) {
    b.score = Math.round(
      b.products.reduce((sum, p) => sum + p.score, 0) / b.products.length
    );
  }

  // Reassign tier based on new score
  if (b.score >= 70) b.tier = "safe";
  else if (b.score >= 45) b.tier = "moderate";
  else b.tier = "high_risk";
});

// Precomputed lookups
export const BRAND_BY_ID = Object.fromEntries(BRANDS.map(b => [b.id, b]));
export const BRAND_BY_NAME = Object.fromEntries(BRANDS.map(b => [b.name.toLowerCase(), b]));
export const BRAND_TIERS = {
  safe: { label: "Low Risk", color: "#16a34a", range: "70-100" },
  moderate: { label: "Moderate", color: "#ca8a04", range: "45-69" },
  high_risk: { label: "High Risk", color: "#dc2626", range: "0-44" },
};
export const BRAND_CATEGORIES = [...new Set(BRANDS.flatMap(b => b.products.map(p => p.cat)))].sort();
