// ============================================================
// CleanWear Brand Health Database
// Each brand scored on chemical safety based on:
//   - Typical materials used across product lines
//   - Known certifications held
//   - Manufacturing transparency
//   - Chemical treatment practices
// Score = 0-100 (same scale as product scores)
// ============================================================

export const BRANDS = [
  // ---- SAFE TIER (70-100) ----
  { id: "patagonia", name: "Patagonia", score: 91, logo: "🏔️", tier: "safe",
    summary: "Industry leader in material transparency. GOTS organic cotton, bluesign-approved supply chain, Fair Trade certified factories.",
    materials: ["Organic Cotton", "Recycled Polyester", "Hemp", "NetPlus Recycled Nylon"],
    certs: ["GOTS", "bluesign", "Fair Trade"],
    chemicals: [], origin: "Vietnam, Sri Lanka, USA",
    products: [
      { name: "Organic Cotton Tee", score: 92, cat: "Casual" },
      { name: "Nano Puff Jacket", score: 45, cat: "Outerwear" },
      { name: "Capilene Cool Shirt", score: 48, cat: "Athletic" },
      { name: "Stand Up Shorts", score: 85, cat: "Casual" },
    ]},
  { id: "pact", name: "Pact", score: 93, logo: "🌿", tier: "safe",
    summary: "Certified organic cotton across entire line. GOTS certified, Fair Trade factories. One of the cleanest mass-market brands.",
    materials: ["Organic Cotton", "Organic Cotton/Spandex"],
    certs: ["GOTS", "Fair Trade"],
    chemicals: ["phthalates"], origin: "India, Turkey",
    products: [
      { name: "Organic Boxer Briefs", score: 91, cat: "Underwear" },
      { name: "Organic Bralette", score: 90, cat: "Underwear" },
      { name: "Organic Crew Tee", score: 92, cat: "Casual" },
      { name: "Organic Leggings", score: 88, cat: "Athletic" },
    ]},
  { id: "smartwool", name: "Smartwool", score: 88, logo: "🐑", tier: "safe",
    summary: "Merino wool core — naturally antimicrobial without chemical treatments. Minimal synthetic content.",
    materials: ["Merino Wool", "Nylon (trace)"],
    certs: ["bluesign", "ZQ Merino"],
    chemicals: [], origin: "Vietnam, China",
    products: [
      { name: "Merino 250 Base Layer", score: 87, cat: "Athletic" },
      { name: "Hike Classic Sock", score: 90, cat: "Athletic" },
      { name: "Classic Thermal Merino", score: 88, cat: "Casual" },
    ]},
  { id: "allbirds", name: "Allbirds", score: 82, logo: "🌳", tier: "safe",
    summary: "Merino wool, eucalyptus TENCEL, and sugarcane-based materials. Transparent carbon footprint labeling.",
    materials: ["Merino Wool", "TENCEL Lyocell", "Sugarcane EVA"],
    certs: ["B Corp", "Climate Neutral"],
    chemicals: [], origin: "Vietnam, South Korea",
    products: [
      { name: "Wool Runner", score: 84, cat: "Casual" },
      { name: "Tree Dasher", score: 78, cat: "Athletic" },
      { name: "Trino Tee", score: 80, cat: "Casual" },
    ]},
  { id: "coyuchi", name: "Coyuchi", score: 94, logo: "🛏️", tier: "safe",
    summary: "100% organic cotton bedding and sleepwear. GOTS certified. Gold standard for what touches your skin while sleeping.",
    materials: ["Organic Cotton"],
    certs: ["GOTS", "Fair Trade"],
    chemicals: [], origin: "India, Portugal",
    products: [
      { name: "Organic Pajama Set", score: 93, cat: "Sleepwear" },
      { name: "Organic Sheet Set", score: 95, cat: "Sleepwear" },
    ]},
  { id: "prana", name: "prAna", score: 85, logo: "🧘", tier: "safe",
    summary: "Heavy use of organic cotton, recycled materials, and hemp. Fair Trade certified factories.",
    materials: ["Organic Cotton", "Hemp", "Recycled Polyester"],
    certs: ["Fair Trade", "bluesign"],
    chemicals: [], origin: "Multiple (transparent)",
    products: [
      { name: "Hemp Tee", score: 89, cat: "Casual" },
      { name: "Stretch Zion Pant", score: 72, cat: "Casual" },
      { name: "Bridger Jean", score: 78, cat: "Casual" },
    ]},
  { id: "icebreaker", name: "Icebreaker", score: 86, logo: "❄️", tier: "safe",
    summary: "Merino wool specialist. Natural fiber-first approach with transparent supply chain tracing.",
    materials: ["Merino Wool", "TENCEL"],
    certs: ["bluesign", "ZQ Merino"],
    chemicals: [], origin: "Vietnam, China",
    products: [
      { name: "200 Oasis Base Layer", score: 88, cat: "Athletic" },
      { name: "Merino Tech Lite Tee", score: 86, cat: "Casual" },
    ]},
  { id: "burts_bees", name: "Burt's Bees Baby", score: 92, logo: "🐝", tier: "safe",
    summary: "100% organic cotton baby clothing. GOTS certified. Critical for infant chemical safety.",
    materials: ["Organic Cotton"],
    certs: ["GOTS"],
    chemicals: [], origin: "India",
    products: [
      { name: "Organic Onesie", score: 92, cat: "Kids" },
      { name: "Organic Sleep & Play", score: 93, cat: "Kids" },
    ]},

  // ---- MODERATE TIER (45-69) ----
  { id: "levis", name: "Levi's", score: 67, logo: "👖", tier: "moderate",
    summary: "Cotton-heavy product line reduces chemical risk. Water<Less program reduces processing chemicals. Some synthetic blends in stretch denim.",
    materials: ["Cotton", "Cotton/Elastane"],
    certs: [],
    chemicals: ["formaldehyde", "phthalates"], origin: "Multiple countries",
    products: [
      { name: "501 Original Jeans", score: 70, cat: "Casual" },
      { name: "505 Regular Jeans", score: 64, cat: "Casual" },
      { name: "Trucker Jacket", score: 72, cat: "Outerwear" },
    ]},
  { id: "uniqlo", name: "Uniqlo", score: 62, logo: "🔲", tier: "moderate",
    summary: "Mixed bag. Cotton basics are decent, but HEATTECH and AIRism lines are heavily synthetic with chemical treatments.",
    materials: ["Cotton", "Polyester", "Nylon/Spandex blends"],
    certs: [],
    chemicals: ["formaldehyde", "antimony"], origin: "China, Vietnam, Bangladesh",
    products: [
      { name: "Supima Cotton Tee", score: 72, cat: "Casual" },
      { name: "HEATTECH Ultra Warm", score: 32, cat: "Athletic" },
      { name: "AIRism Boxer Briefs", score: 35, cat: "Underwear" },
      { name: "Essential Tee", score: 68, cat: "Casual" },
    ]},
  { id: "hm", name: "H&M", score: 52, logo: "🏷️", tier: "moderate",
    summary: "Conscious Choice line scores better, but core line is fast fashion with chemical treatments. Inconsistent across products.",
    materials: ["Cotton", "Polyester", "Viscose"],
    certs: ["OEKO-TEX (select items)"],
    chemicals: ["formaldehyde", "antimony", "phthalates"], origin: "Bangladesh, China, Turkey",
    products: [
      { name: "Conscious Cotton Tee", score: 65, cat: "Casual" },
      { name: "Regular Fit Jeans", score: 58, cat: "Casual" },
      { name: "Sports Tights", score: 30, cat: "Athletic" },
    ]},
  { id: "gap", name: "Gap", score: 58, logo: "🇺🇸", tier: "moderate",
    summary: "Cotton-forward basics keep it moderate. Limited chemical transparency. Athleta sub-brand scores better.",
    materials: ["Cotton", "Cotton/Polyester blends"],
    certs: [],
    chemicals: ["formaldehyde"], origin: "Vietnam, China, India",
    products: [
      { name: "Classic Pocket Tee", score: 66, cat: "Casual" },
      { name: "Vintage Wash Jeans", score: 60, cat: "Casual" },
    ]},
  { id: "carhartt", name: "Carhartt", score: 58, logo: "🔨", tier: "moderate",
    summary: "Heavy cotton construction is a plus. But poly/cotton blends and stain-resistant treatments add chemical load.",
    materials: ["Cotton", "Cotton/Polyester", "Nylon"],
    certs: [],
    chemicals: ["formaldehyde", "antimony"], origin: "Multiple countries",
    products: [
      { name: "Pocket Tee", score: 66, cat: "Casual" },
      { name: "Fleece Hoodie", score: 55, cat: "Casual" },
      { name: "Rain Defender Jacket", score: 38, cat: "Outerwear" },
    ]},
  { id: "calvin_klein", name: "Calvin Klein", score: 55, logo: "🩲", tier: "moderate",
    summary: "Underwear line is mostly cotton (decent). Performance and athleisure lines shift to synthetics with higher chemical risk.",
    materials: ["Cotton", "Modal", "Polyester/Elastane"],
    certs: [],
    chemicals: ["formaldehyde", "phthalates"], origin: "Multiple countries",
    products: [
      { name: "Classic Boxer Brief", score: 62, cat: "Underwear" },
      { name: "Cotton Stretch Trunk", score: 64, cat: "Underwear" },
      { name: "Performance Tee", score: 36, cat: "Athletic" },
    ]},
  { id: "brooks_brothers", name: "Brooks Brothers", score: 64, logo: "👔", tier: "moderate",
    summary: "Traditional cotton and wool suiting scores well. Non-iron/wrinkle-free shirts use formaldehyde treatments.",
    materials: ["Cotton", "Wool", "Cotton/Polyester"],
    certs: [],
    chemicals: ["formaldehyde"], origin: "Multiple countries",
    products: [
      { name: "Classic Oxford Shirt", score: 70, cat: "Casual" },
      { name: "Non-Iron Dress Shirt", score: 48, cat: "Casual" },
      { name: "Wool Suit", score: 80, cat: "Casual" },
    ]},

  // ---- HIGH RISK TIER (0-44) ----
  { id: "nike", name: "Nike", score: 35, logo: "✓", tier: "high_risk",
    summary: "Dominant polyester/nylon/spandex across performance lines. Dri-FIT technology relies on synthetic chemical treatments. High chemical absorption during exercise.",
    materials: ["Polyester", "Nylon", "Spandex", "Recycled Polyester"],
    certs: ["bluesign (select)"],
    chemicals: ["antimony", "microplastics", "bpa", "phthalates"], origin: "Vietnam, China, Indonesia",
    products: [
      { name: "Dri-FIT Tee", score: 34, cat: "Athletic" },
      { name: "Tech Fleece Hoodie", score: 32, cat: "Athletic" },
      { name: "Pro Compression Tights", score: 26, cat: "Athletic" },
      { name: "Kids Dri-FIT Tee", score: 33, cat: "Kids" },
    ]},
  { id: "adidas", name: "Adidas", score: 37, logo: "⫼", tier: "high_risk",
    summary: "Heavily synthetic. Climalite and AEROREADY are polyester-based with chemical moisture management. Some Parley ocean plastic lines.",
    materials: ["Polyester", "Recycled Polyester", "Nylon/Elastane"],
    certs: [],
    chemicals: ["antimony", "microplastics", "bpa", "phthalates"], origin: "Vietnam, China, Indonesia",
    products: [
      { name: "AEROREADY Tee", score: 36, cat: "Athletic" },
      { name: "Ultraboost Running Shoe", score: 34, cat: "Athletic" },
      { name: "Tiro Track Pants", score: 33, cat: "Athletic" },
    ]},
  { id: "under_armour", name: "Under Armour", score: 32, logo: "🛡️", tier: "high_risk",
    summary: "Almost entirely synthetic performance fabrics. HeatGear and ColdGear are polyester/elastane with extensive chemical treatments.",
    materials: ["Polyester", "Elastane", "Nylon"],
    certs: [],
    chemicals: ["antimony", "microplastics", "bpa", "phthalates", "formaldehyde"], origin: "Jordan, China, Vietnam",
    products: [
      { name: "HeatGear Compression", score: 30, cat: "Athletic" },
      { name: "ColdGear Base Layer", score: 28, cat: "Athletic" },
      { name: "Tech 2.0 Tee", score: 33, cat: "Athletic" },
    ]},
  { id: "lululemon", name: "Lululemon", score: 31, logo: "🧘", tier: "high_risk",
    summary: "Premium price, but Nulu/Luon/Everlux fabrics are nylon-spandex blends. High skin contact + exercise = maximum chemical absorption.",
    materials: ["Nylon", "Lycra", "Polyester"],
    certs: [],
    chemicals: ["microplastics", "phthalates", "formaldehyde"], origin: "Vietnam, Cambodia, Sri Lanka",
    products: [
      { name: "Align Leggings", score: 29, cat: "Athletic" },
      { name: "Swiftly Tech Tee", score: 31, cat: "Athletic" },
      { name: "Wunder Train Leggings", score: 30, cat: "Athletic" },
    ]},
  { id: "gymshark", name: "Gymshark", score: 32, logo: "🦈", tier: "high_risk",
    summary: "Fast-growing but entirely synthetic. Polyester/nylon/elastane across all products. No certifications, limited transparency.",
    materials: ["Polyester", "Nylon", "Elastane"],
    certs: [],
    chemicals: ["antimony", "microplastics", "phthalates", "bpa"], origin: "China, Vietnam, Bangladesh",
    products: [
      { name: "Vital Seamless Tee", score: 32, cat: "Athletic" },
      { name: "Gym Shorts", score: 31, cat: "Athletic" },
      { name: "Instinct Shorts", score: 33, cat: "Athletic" },
    ]},
  { id: "2xu", name: "2XU", score: 28, logo: "🏋️", tier: "high_risk",
    summary: "Compression specialist — the tightest skin contact in the industry combined with fully synthetic materials. Maximum chemical transfer.",
    materials: ["Nylon", "Elastane", "Polyester"],
    certs: [],
    chemicals: ["microplastics", "phthalates", "formaldehyde", "bpa"], origin: "China",
    products: [
      { name: "Compression Tights", score: 28, cat: "Athletic" },
      { name: "Core Compression Shorts", score: 27, cat: "Athletic" },
    ]},
  { id: "victorias_secret", name: "Victoria's Secret", score: 34, logo: "💗", tier: "high_risk",
    summary: "Intimate apparel in nylon/polyester with high skin contact zones. Bras, underwear, and sleepwear all synthetic-heavy.",
    materials: ["Nylon", "Polyester", "Elastane"],
    certs: [],
    chemicals: ["microplastics", "phthalates", "formaldehyde"], origin: "Sri Lanka, Vietnam, China",
    products: [
      { name: "Seamless Thong", score: 35, cat: "Underwear" },
      { name: "Satin Pajamas", score: 38, cat: "Sleepwear" },
      { name: "Sports Bra", score: 28, cat: "Athletic" },
    ]},
  { id: "shein", name: "Shein", score: 18, logo: "⚡", tier: "high_risk",
    summary: "Lowest scores in database. Ultra-fast fashion with minimal quality control. Studies have found elevated lead, PFAS, and formaldehyde levels.",
    materials: ["Polyester", "Cotton/Polyester blends", "Acrylic"],
    certs: [],
    chemicals: ["antimony", "microplastics", "formaldehyde", "phthalates", "azo_dyes", "heavy_metals"], origin: "China",
    products: [
      { name: "Basic Crop Top", score: 18, cat: "Casual" },
      { name: "Workout Set", score: 15, cat: "Athletic" },
      { name: "Kids Graphic Tee", score: 16, cat: "Kids" },
    ]},
  { id: "temu", name: "Temu", score: 16, logo: "📦", tier: "high_risk",
    summary: "Unregulated marketplace. No quality oversight on chemical content. Products frequently fail safety testing in independent studies.",
    materials: ["Unknown synthetics", "Polyester blends"],
    certs: [],
    chemicals: ["antimony", "microplastics", "formaldehyde", "phthalates", "azo_dyes", "heavy_metals", "bpa"], origin: "China",
    products: [
      { name: "Generic Activewear Set", score: 14, cat: "Athletic" },
      { name: "Kids Clothing Pack", score: 12, cat: "Kids" },
    ]},
  { id: "fashion_nova", name: "Fashion Nova", score: 22, logo: "🌟", tier: "high_risk",
    summary: "Fast fashion with heavy synthetic content. Minimal ingredient/material disclosure. Targets young women with high-contact bodycon styles.",
    materials: ["Polyester", "Nylon", "Rayon"],
    certs: [],
    chemicals: ["antimony", "microplastics", "formaldehyde", "phthalates", "azo_dyes"], origin: "China, USA (some)",
    products: [
      { name: "Bodycon Dress", score: 20, cat: "Casual" },
      { name: "High Waist Leggings", score: 22, cat: "Athletic" },
    ]},
  { id: "boohoo", name: "Boohoo", score: 20, logo: "💅", tier: "high_risk",
    summary: "Ultra-fast fashion with documented supply chain issues. Synthetic-heavy, minimal safety testing disclosure.",
    materials: ["Polyester", "Viscose", "Nylon"],
    certs: [],
    chemicals: ["antimony", "microplastics", "formaldehyde", "phthalates", "azo_dyes"], origin: "UK, China, Bangladesh",
    products: [
      { name: "Mesh Bodysuit", score: 18, cat: "Casual" },
      { name: "Jersey Joggers", score: 25, cat: "Casual" },
    ]},

  // ---- MORE MODERATE ----
  { id: "north_face", name: "The North Face", score: 42, logo: "⛰️", tier: "high_risk",
    summary: "Outerwear relies on nylon and polyester with DWR coatings (PFAS risk). Some Futurelight items moving toward PFC-free.",
    materials: ["Nylon", "Polyester", "Gore-Tex"],
    certs: ["bluesign (select)"],
    chemicals: ["microplastics", "pfas", "formaldehyde"], origin: "Vietnam, China, Bangladesh",
    products: [
      { name: "Thermoball Jacket", score: 36, cat: "Outerwear" },
      { name: "Reaxion Tee", score: 34, cat: "Athletic" },
      { name: "Denali Fleece", score: 40, cat: "Outerwear" },
    ]},
  { id: "jcrew", name: "J.Crew", score: 68, logo: "⚓", tier: "moderate",
    summary: "Linen and cotton-heavy product lines score well. Some synthetic blends in performance and stretch items.",
    materials: ["Cotton", "Linen", "Wool", "Cotton/Polyester"],
    certs: [],
    chemicals: ["formaldehyde"], origin: "Multiple countries",
    products: [
      { name: "Linen Camp Shirt", score: 84, cat: "Casual" },
      { name: "Broken-in Tee", score: 68, cat: "Casual" },
      { name: "Wool Overcoat", score: 82, cat: "Outerwear" },
    ]},
  { id: "hanes", name: "Hanes", score: 60, logo: "📦", tier: "moderate",
    summary: "Cotton underwear and basics are decent. ComfortSoft line is mostly cotton. Performance lines shift to synthetics.",
    materials: ["Cotton", "Cotton/Polyester"],
    certs: [],
    chemicals: ["formaldehyde"], origin: "Honduras, El Salvador, USA",
    products: [
      { name: "ComfortSoft Tee", score: 66, cat: "Casual" },
      { name: "Cotton Boxer Briefs", score: 64, cat: "Underwear" },
      { name: "Cool DRI Tee", score: 34, cat: "Athletic" },
    ]},
  { id: "new_balance", name: "New Balance", score: 38, logo: "NB", tier: "high_risk",
    summary: "Athletic focus means synthetic-heavy. Some Made in USA products with better oversight, but core line is standard polyester/nylon.",
    materials: ["Polyester", "Nylon", "Mesh synthetics"],
    certs: [],
    chemicals: ["antimony", "microplastics", "phthalates"], origin: "USA (some), China, Vietnam",
    products: [
      { name: "Impact Run Tee", score: 36, cat: "Athletic" },
      { name: "Essentials Hoodie", score: 52, cat: "Casual" },
    ]},
  { id: "amazon_essentials", name: "Amazon Essentials", score: 50, logo: "📦", tier: "moderate",
    summary: "Budget basics. Cotton items are acceptable, but no certifications and minimal transparency on chemical treatments.",
    materials: ["Cotton", "Polyester", "Cotton/Polyester blends"],
    certs: [],
    chemicals: ["formaldehyde", "antimony"], origin: "Various",
    products: [
      { name: "Crewneck Tee 2-Pack", score: 58, cat: "Casual" },
      { name: "Performance Tee", score: 34, cat: "Athletic" },
    ]},
  { id: "vuori", name: "Vuori", score: 44, logo: "🌊", tier: "high_risk",
    summary: "Premium athleisure but still polyester/elastane core. Some recycled content. Better transparency than most athletic brands but same base materials.",
    materials: ["Recycled Polyester", "Elastane", "Nylon"],
    certs: [],
    chemicals: ["antimony", "microplastics", "phthalates"], origin: "China, Vietnam",
    products: [
      { name: "Strato Tech Tee", score: 42, cat: "Athletic" },
      { name: "Kore Shorts", score: 40, cat: "Athletic" },
    ]},
];

// Precomputed lookups
export const BRAND_BY_ID = Object.fromEntries(BRANDS.map(b => [b.id, b]));
export const BRAND_TIERS = {
  safe: { label: "Low Risk", color: "#4ade80", range: "70-100" },
  moderate: { label: "Moderate", color: "#facc15", range: "45-69" },
  high_risk: { label: "High Risk", color: "#f87171", range: "0-44" },
};
export const BRAND_CATEGORIES = [...new Set(BRANDS.flatMap(b => b.products.map(p => p.cat)))].sort();
